---
- name: Create standard directory for libresbc 
  ansible.builtin.file:
    path: /opt/libresbc
    owner: root
    group: root
    mode: "0644"
    state: directory

- name: Download libreui
  ansible.builtin.get_url:
    url: https://github.com/hnimminh/repository/raw/42b29addb4590a10753b234279c614fac5e5a196/libreui-linux-amd64
    dest: "/opt/libresbc/libreui"
    mode: '0755'
    checksum: md5:49fa0c6c23ad4afa268a2013a4c50c34
  changed_when: true
  notify:
    - restart libreui

- name: copy libreui service
  copy:
    src: libreui.service
    dest: /etc/systemd/system/libreui.service
    owner: root
    group: root
    mode: 0644

#- name: Symbolic link for primary location (libreui)
#  file:
#    src: "{{item.src}}"
#    dest: "{{item.dest}}"
#    force: true
#    state: link
#  with_items:
#    - src: "/opt/libresbc/libreui-linux-amd64"
#      dest: /opt/libresbc/libreui
...
